version: '3'

services:
  webserver:
    image: apache/airflow:2.1.0-python3.8
    ports:
      - "8080:8080"
    environment:
      - LOAD_EX=n
      - EXECUTOR=Local
    command: webserver

  scheduler:
    image: apache/airflow:2.1.0-python3.8
    environment:
      - LOAD_EX=n
      - EXECUTOR=Local
    command: scheduler

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow

  pyspark-notebook:
    image: jupyter/pyspark-notebook:latest
    ports:
      - "8888:8888"
    volumes:
      - ./jupyter_notebook_config.py:/home/jovyan/.jupyter/jupyter_notebook_config.py

  spark-master:
    image: bitnami/spark:latest
    ports:
      - "8081:8081"
    environment:
      - SPARK_MODE=master

  spark-worker:
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    deploy:
      replicas: 3

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./www:/usr/share/nginx/html

networks:
  default:
    external:
      name: nginx-network
